# Project-wide Gradle settings for PSBDx DevBrowser.

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# JVM args for the Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable Gradle's parallel & caching features
org.gradle.parallel=true
org.gradle.caching=true
